PACKAGE_NAME="rcraid"
PACKAGE_VERSION="8.1.0"
BUILT_MODULE_NAME[0]="rcraid"
DEST_MODULE_LOCATION[0]="/kernel/drivers/scsi"
AUTOINSTALL="yes"
MAKE[0]="make"
CLEAN="make clean"
BUILD_EXCLUSIVE_KERNEL="^5\.[0-9]+|^6\.[0-9]+|^7\.[0-9]+"
REMAKE_INITRD="yes"
